on:
  push:
    branches:
      - 'main'

jobs:
  make-release:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Push to Cocoapod
      #   env: 
      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.POD_TRUNK_TOKEN }}
      #   run: pod trunk push UserLeapKit.podspec
      - name: Get Version
        id: get-version
        run: echo "version=$(grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+" UserLeapKit.podspec)" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: bash ./scripts/tag-and-release.sh tag ${{ secrets.GH_TOKEN }} ${{ steps.get-version.outputs.version }}

      - name: Create release
        run: bash ./scripts/tag-and-release.sh release ${{ secrets.GH_TOKEN }} ${{ steps.get-version.outputs.version }}